### ISSUE TITLE
Upgrade of the openssl cookbook

### ISSUE THREAD

**Issue by zedtux** [EugenMayer/chef-tinc-cookbook#34]
The `openssl` cookbook version is quite old and we are seeing those warnings:

```
WARN: Resource openssl_dhparam built into Chef Infra Client is being overridden by the resource from a cookbook. Please upgrade your cookbook or remove the cookbook from your run_list.
WARN: Resource openssl_rsa_key built into Chef Infra Client is being overridden by the resource from a cookbook. Please upgrade your cookbook or remove the cookbook from your run_list.
WARN: Resource openssl_x509 built into Chef Infra Client is being overridden by the resource from a cookbook. Please upgrade your cookbook or remove the cookbook from your run_list.
```

Upgrading the cookbook should fix that.

**Comment by EugenMayer** [comment]
make sense and i'am fairly sure it would not break anything.

The problem is https://supermarket.chef.io/cookbooks/openssl/versions/8.5.5 .. they are on 8 now, so a 4 times major jump,

https://github.com/chef-boneyard/openssl/blob/master/CHANGELOG.md,



- https://github.com/chef-boneyard/openssl/blob/master/CHANGELOG.md#500-2016-08-27  seems uncritical
- https://github.com/chef-boneyard/openssl/blob/master/CHANGELOG.md#600-2016-09-08 might be relevant, chef 12+ only (for me it's fine, i'am 13+ right now, but we will need to make it a major too then, if we go from chef 11 to 12 imho). Sit would rather be a 2.0.0 on our side)
- https://github.com/chef-boneyard/openssl/blob/master/CHANGELOG.md#800-2017-12-11 is a lot, but it seems rather internal improvment, fixes and new features

so i would say, lets go for 8.5.5 and ensure the tests run, then aim for 2.0.0 - what do you think?

**Comment by zedtux** [comment]
I fully agree with you, I'll proceed that way, thank you for your input !
